#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/uart.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_45

#define AUDIO_CODEC_PA_PIN      GPIO_NUM_39
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR 0x82

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define U1_UART_PORT_NUM  UART_NUM_1
#define U1_UART_BAUD_RATE 115200
// U8 的 TX 必须接到 U1 的 RX。按硬件文档：
//   U8.IO11 = M_U1TXD (U8 发给 U1) → U1.IO11 = M_U1RXD
//   U8.IO10 = M_U1RXD (U8 收自 U1) ← U1.IO10 = M_U1TXD
// 之前此处 TX/RX 对调，导致 UART 双向哑通道。
#define U1_UART_TXD       GPIO_NUM_11
#define U1_UART_RXD       GPIO_NUM_10
#define U1_UART_RTS       UART_PIN_NO_CHANGE
#define U1_UART_CTS       UART_PIN_NO_CHANGE
#define U1_UART_BUF_SIZE  1024

#define CAMERA_PIN_PWDN  GPIO_NUM_40
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define CAMERA_PIN_XCLK  GPIO_NUM_5
#define CAMERA_PIN_SIOD  GPIO_NUM_1
#define CAMERA_PIN_SIOC  GPIO_NUM_2

#define CAMERA_PIN_D7    GPIO_NUM_9
#define CAMERA_PIN_D6    GPIO_NUM_4
#define CAMERA_PIN_D5    GPIO_NUM_6
#define CAMERA_PIN_D4    GPIO_NUM_15
#define CAMERA_PIN_D3    GPIO_NUM_17
#define CAMERA_PIN_D2    GPIO_NUM_8
#define CAMERA_PIN_D1    GPIO_NUM_18
#define CAMERA_PIN_D0    GPIO_NUM_16
#define CAMERA_PIN_VSYNC GPIO_NUM_3
#define CAMERA_PIN_HREF  GPIO_NUM_46
#define CAMERA_PIN_PCLK  GPIO_NUM_7

#define XCLK_FREQ_HZ 24000000

#endif // _BOARD_CONFIG_H_
